INSERT INTO nationality VALUES (1,'Afghan');
INSERT INTO nationality VALUES (2,'Albanian');
INSERT INTO nationality VALUES (3,'Algerian');
INSERT INTO nationality VALUES (4,'American');
INSERT INTO nationality VALUES (5,'Andorran');
INSERT INTO nationality VALUES (6,'Angolan');
INSERT INTO nationality VALUES (7,'Antiguans');
INSERT INTO nationality VALUES (8,'Argentinean');
INSERT INTO nationality VALUES (9,'Armenian');
INSERT INTO nationality VALUES (10,'Australian');
INSERT INTO nationality VALUES (11,'Austrian');
INSERT INTO nationality VALUES (12,'Azerbaijani');
INSERT INTO nationality VALUES (13,'Bahamian');
INSERT INTO nationality VALUES (14,'Bahraini');
INSERT INTO nationality VALUES (15,'Bangladeshi');
INSERT INTO nationality VALUES (16,'Barbadian');
INSERT INTO nationality VALUES (17,'Barbudans');
INSERT INTO nationality VALUES (18,'Batswana');
INSERT INTO nationality VALUES (19,'Belarusian');
INSERT INTO nationality VALUES (20,'Belgian');
INSERT INTO nationality VALUES (21,'Belizean');
INSERT INTO nationality VALUES (22,'Beninese');
INSERT INTO nationality VALUES (23,'Bhutanese');
INSERT INTO nationality VALUES (24,'Bolivian');
INSERT INTO nationality VALUES (25,'Bosnian');
INSERT INTO nationality VALUES (26,'Brazilian');
INSERT INTO nationality VALUES (27,'British');
INSERT INTO nationality VALUES (28,'Bruneian');
INSERT INTO nationality VALUES (29,'Bulgarian');
INSERT INTO nationality VALUES (30,'Burkinabe');
INSERT INTO nationality VALUES (31,'Burmese');
INSERT INTO nationality VALUES (32,'Burundian');
INSERT INTO nationality VALUES (33,'Cambodian');
INSERT INTO nationality VALUES (34,'Cameroonian');
INSERT INTO nationality VALUES (35,'Canadian');
INSERT INTO nationality VALUES (36,'Cape Verdean');
INSERT INTO nationality VALUES (37,'Central African');
INSERT INTO nationality VALUES (38,'Chadian');
INSERT INTO nationality VALUES (39,'Chilean');
INSERT INTO nationality VALUES (40,'Chinese');
INSERT INTO nationality VALUES (41,'Colombian');
INSERT INTO nationality VALUES (42,'Comoran');
INSERT INTO nationality VALUES (43,'Congolese');
INSERT INTO nationality VALUES (44,'Costa Rican');
INSERT INTO nationality VALUES (45,'Croatian');
INSERT INTO nationality VALUES (46,'Cuban');
INSERT INTO nationality VALUES (47,'Cypriot');
INSERT INTO nationality VALUES (48,'Czech');
INSERT INTO nationality VALUES (49,'Danish');
INSERT INTO nationality VALUES (50,'Djibouti');
INSERT INTO nationality VALUES (51,'Dominican');
INSERT INTO nationality VALUES (52,'Dutch');
INSERT INTO nationality VALUES (53,'East Timorese');
INSERT INTO nationality VALUES (54,'Ecuadorean');
INSERT INTO nationality VALUES (55,'Egyptian');
INSERT INTO nationality VALUES (56,'Emirian');
INSERT INTO nationality VALUES (57,'Equatorial Guinean');
INSERT INTO nationality VALUES (58,'Eritrean');
INSERT INTO nationality VALUES (59,'Estonian');
INSERT INTO nationality VALUES (60,'Ethiopian');
INSERT INTO nationality VALUES (61,'Fijian');
INSERT INTO nationality VALUES (62,'Filipino');
INSERT INTO nationality VALUES (63,'Finnish');
INSERT INTO nationality VALUES (64,'French');
INSERT INTO nationality VALUES (65,'Gabonese');
INSERT INTO nationality VALUES (66,'Gambian');
INSERT INTO nationality VALUES (67,'Georgian');
INSERT INTO nationality VALUES (68,'German');
INSERT INTO nationality VALUES (69,'Ghanaian');
INSERT INTO nationality VALUES (70,'Greek');
INSERT INTO nationality VALUES (71,'Grenadian');
INSERT INTO nationality VALUES (72,'Guatemalan');
INSERT INTO nationality VALUES (73,'Guinea-Bissauan');
INSERT INTO nationality VALUES (74,'Guinean');
INSERT INTO nationality VALUES (75,'Guyanese');
INSERT INTO nationality VALUES (76,'Haitian');
INSERT INTO nationality VALUES (77,'Herzegovinian');
INSERT INTO nationality VALUES (78,'Honduran');
INSERT INTO nationality VALUES (79,'Hungarian');
INSERT INTO nationality VALUES (80,'I-Kiribati');
INSERT INTO nationality VALUES (81,'Icelander');
INSERT INTO nationality VALUES (82,'Indian');
INSERT INTO nationality VALUES (83,'Indonesian');
INSERT INTO nationality VALUES (84,'Iranian');
INSERT INTO nationality VALUES (85,'Iraqi');
INSERT INTO nationality VALUES (86,'Irish');
INSERT INTO nationality VALUES (87,'Israeli');
INSERT INTO nationality VALUES (88,'Italian');
INSERT INTO nationality VALUES (89,'Ivorian');
INSERT INTO nationality VALUES (90,'Jamaican');
INSERT INTO nationality VALUES (91,'Japanese');
INSERT INTO nationality VALUES (92,'Jordanian');
INSERT INTO nationality VALUES (93,'Kazakhstani');
INSERT INTO nationality VALUES (94,'Kenyan');
INSERT INTO nationality VALUES (95,'Kittian and Nevisian');
INSERT INTO nationality VALUES (96,'Kuwaiti');
INSERT INTO nationality VALUES (97,'Kyrgyz');
INSERT INTO nationality VALUES (98,'Laotian');
INSERT INTO nationality VALUES (99,'Latvian');
INSERT INTO nationality VALUES (100,'Lebanese');
INSERT INTO nationality VALUES (101,'Liberian');
INSERT INTO nationality VALUES (102,'Libyan');
INSERT INTO nationality VALUES (103,'Liechtensteiner');
INSERT INTO nationality VALUES (104,'Lithuanian');
INSERT INTO nationality VALUES (105,'Luxembourger');
INSERT INTO nationality VALUES (106,'Macedonian');
INSERT INTO nationality VALUES (107,'Malagasy');
INSERT INTO nationality VALUES (108,'Malawian');
INSERT INTO nationality VALUES (109,'Malaysian');
INSERT INTO nationality VALUES (110,'Maldivan');
INSERT INTO nationality VALUES (111,'Malian');
INSERT INTO nationality VALUES (112,'Maltese');
INSERT INTO nationality VALUES (113,'Marshallese');
INSERT INTO nationality VALUES (114,'Mauritanian');
INSERT INTO nationality VALUES (115,'Mauritian');
INSERT INTO nationality VALUES (116,'Mexican');
INSERT INTO nationality VALUES (117,'Micronesian');
INSERT INTO nationality VALUES (118,'Moldovan');
INSERT INTO nationality VALUES (119,'Monacan');
INSERT INTO nationality VALUES (120,'Mongolian');
INSERT INTO nationality VALUES (121,'Moroccan');
INSERT INTO nationality VALUES (122,'Mosotho');
INSERT INTO nationality VALUES (123,'Motswana');
INSERT INTO nationality VALUES (124,'Mozambican');
INSERT INTO nationality VALUES (125,'Namibian');
INSERT INTO nationality VALUES (126,'Nauruan');
INSERT INTO nationality VALUES (127,'Nepalese');
INSERT INTO nationality VALUES (128,'New Zealander');
INSERT INTO nationality VALUES (129,'Nicaraguan');
INSERT INTO nationality VALUES (130,'Nigerian');
INSERT INTO nationality VALUES (131,'Nigerien');
INSERT INTO nationality VALUES (132,'North Korean');
INSERT INTO nationality VALUES (133,'Northern Irish');
INSERT INTO nationality VALUES (134,'Norwegian');
INSERT INTO nationality VALUES (135,'Omani');
INSERT INTO nationality VALUES (136,'Pakistani');
INSERT INTO nationality VALUES (137,'Palauan');
INSERT INTO nationality VALUES (138,'Panamanian');
INSERT INTO nationality VALUES (139,'Papua New Guinean');
INSERT INTO nationality VALUES (140,'Paraguayan');
INSERT INTO nationality VALUES (141,'Peruvian');
INSERT INTO nationality VALUES (142,'Polish');
INSERT INTO nationality VALUES (143,'Portuguese');
INSERT INTO nationality VALUES (144,'Qatari');
INSERT INTO nationality VALUES (145,'Romanian');
INSERT INTO nationality VALUES (146,'Russian');
INSERT INTO nationality VALUES (147,'Rwandan');
INSERT INTO nationality VALUES (148,'Saint Lucian');
INSERT INTO nationality VALUES (149,'Salvadoran');
INSERT INTO nationality VALUES (150,'Samoan');
INSERT INTO nationality VALUES (151,'San Marinese');
INSERT INTO nationality VALUES (152,'Sao Tomean');
INSERT INTO nationality VALUES (153,'Saudi');
INSERT INTO nationality VALUES (154,'Scottish');
INSERT INTO nationality VALUES (155,'Senegalese');
INSERT INTO nationality VALUES (156,'Serbian');
INSERT INTO nationality VALUES (157,'Seychellois');
INSERT INTO nationality VALUES (158,'Sierra Leonean');
INSERT INTO nationality VALUES (159,'Singaporean');
INSERT INTO nationality VALUES (160,'Slovakian');
INSERT INTO nationality VALUES (161,'Slovenian');
INSERT INTO nationality VALUES (162,'Solomon Islander');
INSERT INTO nationality VALUES (163,'Somali');
INSERT INTO nationality VALUES (164,'South African');
INSERT INTO nationality VALUES (165,'South Korean');
INSERT INTO nationality VALUES (166,'Spanish');
INSERT INTO nationality VALUES (167,'Sri Lankan');
INSERT INTO nationality VALUES (168,'Sudanese');
INSERT INTO nationality VALUES (169,'Surinamer');
INSERT INTO nationality VALUES (170,'Swazi');
INSERT INTO nationality VALUES (171,'Swedish');
INSERT INTO nationality VALUES (172,'Swiss');
INSERT INTO nationality VALUES (173,'Syrian');
INSERT INTO nationality VALUES (174,'Taiwanese');
INSERT INTO nationality VALUES (175,'Tajik');
INSERT INTO nationality VALUES (176,'Tanzanian');
INSERT INTO nationality VALUES (177,'Thai');
INSERT INTO nationality VALUES (178,'Togolese');
INSERT INTO nationality VALUES (179,'Tongan');
INSERT INTO nationality VALUES (180,'Trinidadian or Tobagonian');
INSERT INTO nationality VALUES (181,'Tunisian');
INSERT INTO nationality VALUES (182,'Turkish');
INSERT INTO nationality VALUES (183,'Tuvaluan');
INSERT INTO nationality VALUES (184,'Ugandan');
INSERT INTO nationality VALUES (185,'Ukrainian');
INSERT INTO nationality VALUES (186,'Uruguayan');
INSERT INTO nationality VALUES (187,'Uzbekistani');
INSERT INTO nationality VALUES (188,'Venezuelan');
INSERT INTO nationality VALUES (189,'Vietnamese');
INSERT INTO nationality VALUES (190,'Welsh');
INSERT INTO nationality VALUES (191,'Yemenite');
INSERT INTO nationality VALUES (192,'Zambian');
INSERT INTO nationality VALUES (193,'Zimbabwean');