INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (196,'Afghanistan','+93',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (197,'Albania','+355',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (198,'Algeria','+213',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (199,'Andorra','+376',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (200,'Angola','+244',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (201,'Antigua and Barbuda','+1-268',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (202,'Argentina','+54',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (203,'Armenia','+374',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (204,'Australia','+61',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (205,'Austria','+43',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (206,'Azerbaijan','+994',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (207,'Bahamas','+1-242',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (208,'Bahrain','+973',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (209,'Bangladesh','+880',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (210,'Barbados','+1-246',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (211,'Belarus','+375',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (212,'Belgium','+32',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (213,'Burma','+95',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (214,'Belize','+501',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (215,'Benin','+229',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (216,'Bhutan','+975',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (217,'Bolivia','+591',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (218,'Bosnia and Herzegovina','+387',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (219,'Botswana','+267',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (220,'Brazil','+55',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (221,'Brunei','+673',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (222,'Bulgaria','+359',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (223,'Burkina Faso','+226',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (224,'Burundi','+257',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (225,'Cambodia','+855',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (226,'Cameroon','+237',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (227,'Canada','+1',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (228,'Cape Verde','+238',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (229,'Central African Republic','+236',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (230,'Chad','+235',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (231,'Chile','+56',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (232,'China','+86',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (233,'Colombia','+57',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (234,'Comoros','+269',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (235,'Congo (Brazzaville)','+242',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (236,'Costa Rica','+506',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (237,'Cote d''Ivoire','+225',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (238,'Croatia','+385',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (239,'Cuba','+53',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (240,'Cyprus','+357',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (241,'Czech Republic','+420',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (242,'Denmark','+45',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (243,'Djibouti','+253',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (244,'Dominica','+1-767',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (245,'Dominican Republic','+1-809',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (246,'Dominican Republic','+1-849',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (247,'Dominican Republic','+1-829 ',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (248,'East Timor (Timor Timur)','+670',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (249,'Ecuador','+593',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (250,'Egypt','+20',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (251,'El Salvador','+503',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (252,'Equatorial Guinea','+240',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (253,'Eritrea','+291',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (254,'Estonia','+372',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (255,'Ethiopia','+251',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (256,'Fiji','+679',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (257,'Finland','+358',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (258,'France','+33',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (259,'Gabon','+241',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (260,'Gambia','+220',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (261,'Georgia','+995',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (262,'Germany','+49',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (263,'Ghana','+233',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (264,'Greece','+30',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (265,'Grenada','+1-473',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (266,'Guatemala','+502',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (267,'Guinea','+224',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (268,'Guinea-Bissau','+245',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (269,'Hong kong','+852',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (270,'Guyana','+592',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (271,'Haiti','+509',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (272,'Honduras','+504',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (273,'Hungary','+36',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (274,'Iceland','+354',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (275,'India','+91',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (276,'Indonesia','+62',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (277,'Iran','+98',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (278,'Iraq','+964',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (279,'Ireland','+353',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (280,'Israel','+972',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (281,'Italy','+39',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (282,'Jamaica','+1-876',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (283,'Japan','+81',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (284,'Jordan','+962',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (285,'Kazakhstan','+7',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (286,'Kenya','+254',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (287,'Kiribati','+686',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (288,'Kuwait','+965',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (289,'Kyrgyzstan','+996',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (290,'Laos','+856',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (291,'Latvia','+371',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (292,'Lebanon','+961',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (293,'Lesotho','+266',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (294,'Liberia','+231',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (295,'Libya','+218',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (296,'Liechtenstein','+423',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (297,'Lithuania','+370',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (298,'Luxembourg','+352',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (299,'Macedonia','+389',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (300,'Madagascar','+261',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (301,'Malawi','+265',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (302,'Malaysia','+60',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (303,'Maldives','+960',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (304,'Mali','+223',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (305,'Malta','+356',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (306,'Marshall Islands','+692',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (307,'Mauritania','+222',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (308,'Mauritius','+230',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (309,'Montenegro','+382',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (310,'Mexico','+52',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (311,'Micronesia','+691',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (312,'Moldova','+373',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (313,'Monaco','+377',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (314,'Mongolia','+976',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (315,'Morocco','+212',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (316,'Mozambique','+258',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (317,'Myanmar','+95',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (318,'Namibia','+264',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (319,'Nauru','+674',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (320,'North Korea','+850',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (321,'Nepal','+977',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (322,'Netherlands','+31',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (323,'New Zealand','+64',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (324,'Nicaragua','+505',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (325,'Niger','+227',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (326,'Nigeria','+234',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (327,'Norway','+47',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (328,'Oman','+968',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (329,'Pakistan','+92',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (330,'Palau','+680',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (331,'Panama','+507',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (332,'Papua New Guinea','+675',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (333,'Paraguay','+595',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (334,'Peru','+51',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (335,'Philippines','+63',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (336,'Poland','+48',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (337,'Portugal','+351',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (338,'Qatar','+974',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (339,'Romania','+40',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (340,'Russia','+7',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (341,'Rwanda','+250',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (342,'Saint Kitts and Nevis','+1-859',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (343,'Saint Lucia','+1-758',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (344,'Saint Vincent','+1-784',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (345,'Samoa','+685',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (346,'San Marino','+378',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (347,'Sao Tome and Principe','+239',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (348,'Saudi Arabia','+966',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (349,'Senegal','+221',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (350,'Serbia ','+381',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (351,'Seychelles','+248',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (352,'Sierra Leone','+232',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (353,'Singapore','+65',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (354,'Slovakia','+421',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (355,'Slovenia','+386',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (356,'Solomon Islands','+677',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (357,'Somalia','+252',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (358,'South Africa','+27',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (359,'Spain','+34',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (360,'South Korea','+82',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (361,'Sri Lanka','+94',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (362,'Sudan','+249',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (363,'Suriname','+597',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (364,'Swaziland','+268',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (365,'Sweden','+46',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (366,'Switzerland','+41',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (367,'Syria','+963',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (368,'Taiwan','+886',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (369,'Tajikistan','+992',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (370,'Tanzania','+255',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (371,'Thailand','+66',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (372,'Togo','+228',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (373,'Tonga','+676',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (374,'Trinidad and Tobago','+1-868',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (375,'Tunisia','+216',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (376,'Turkey','+90',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (377,'Turkmenistan','+993',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (378,'Tuvalu','+688',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (379,'Uganda','+256',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (380,'Ukraine','+380',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (381,'United Arab Emirates','+971',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (382,'United Kingdom','+44',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (383,'United States','+1',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (384,'Uruguay','+598',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (385,'Uzbekistan','+998',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (386,'Vanuatu','+678',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (387,'Vatican City','+379',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (388,'Venezuela','+58',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (389,'Vietnam','+84',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (390,'Yemen','+967',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (391,'Zambia','+260',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (392,'Zimbabwe','+263',NULL,NULL)
INSERT INTO tblcountry(no,country,code,continent,link_page) VALUES (393,'Congo','+243',NULL,NULL)